// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: services/srs/proto/srs.proto

package srs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentifierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	AuthToken     string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentifierRequest) Reset() {
	*x = IdentifierRequest{}
	mi := &file_services_srs_proto_srs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifierRequest) ProtoMessage() {}

func (x *IdentifierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_srs_proto_srs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifierRequest.ProtoReflect.Descriptor instead.
func (*IdentifierRequest) Descriptor() ([]byte, []int) {
	return file_services_srs_proto_srs_proto_rawDescGZIP(), []int{0}
}

func (x *IdentifierRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *IdentifierRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type KanjiReviewDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Character     string                 `protobuf:"bytes,2,opt,name=character,proto3" json:"character,omitempty"`
	SrsLevel      int32                  `protobuf:"varint,3,opt,name=srs_level,json=srsLevel,proto3" json:"srs_level,omitempty"`
	ReviewTime    int64                  `protobuf:"varint,4,opt,name=review_time,json=reviewTime,proto3" json:"review_time,omitempty"`
	AuthToken     string                 `protobuf:"bytes,5,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KanjiReviewDataRequest) Reset() {
	*x = KanjiReviewDataRequest{}
	mi := &file_services_srs_proto_srs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KanjiReviewDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KanjiReviewDataRequest) ProtoMessage() {}

func (x *KanjiReviewDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_srs_proto_srs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KanjiReviewDataRequest.ProtoReflect.Descriptor instead.
func (*KanjiReviewDataRequest) Descriptor() ([]byte, []int) {
	return file_services_srs_proto_srs_proto_rawDescGZIP(), []int{1}
}

func (x *KanjiReviewDataRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *KanjiReviewDataRequest) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

func (x *KanjiReviewDataRequest) GetSrsLevel() int32 {
	if x != nil {
		return x.SrsLevel
	}
	return 0
}

func (x *KanjiReviewDataRequest) GetReviewTime() int64 {
	if x != nil {
		return x.ReviewTime
	}
	return 0
}

func (x *KanjiReviewDataRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type KanjiReviewDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     string                 `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	SrsLevel      int32                  `protobuf:"varint,2,opt,name=srs_level,json=srsLevel,proto3" json:"srs_level,omitempty"`
	ReviewTime    int64                  `protobuf:"varint,3,opt,name=review_time,json=reviewTime,proto3" json:"review_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KanjiReviewDataResponse) Reset() {
	*x = KanjiReviewDataResponse{}
	mi := &file_services_srs_proto_srs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KanjiReviewDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KanjiReviewDataResponse) ProtoMessage() {}

func (x *KanjiReviewDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_srs_proto_srs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KanjiReviewDataResponse.ProtoReflect.Descriptor instead.
func (*KanjiReviewDataResponse) Descriptor() ([]byte, []int) {
	return file_services_srs_proto_srs_proto_rawDescGZIP(), []int{2}
}

func (x *KanjiReviewDataResponse) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

func (x *KanjiReviewDataResponse) GetSrsLevel() int32 {
	if x != nil {
		return x.SrsLevel
	}
	return 0
}

func (x *KanjiReviewDataResponse) GetReviewTime() int64 {
	if x != nil {
		return x.ReviewTime
	}
	return 0
}

var File_services_srs_proto_srs_proto protoreflect.FileDescriptor

const file_services_srs_proto_srs_proto_rawDesc = "" +
	"\n" +
	"\x1cservices/srs/proto/srs.proto\x12\x13aeriqu.kanikaki.srs\"R\n" +
	"\x11IdentifierRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\"\xb3\x01\n" +
	"\x16KanjiReviewDataRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1c\n" +
	"\tcharacter\x18\x02 \x01(\tR\tcharacter\x12\x1b\n" +
	"\tsrs_level\x18\x03 \x01(\x05R\bsrsLevel\x12\x1f\n" +
	"\vreview_time\x18\x04 \x01(\x03R\n" +
	"reviewTime\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x05 \x01(\tR\tauthToken\"u\n" +
	"\x17KanjiReviewDataResponse\x12\x1c\n" +
	"\tcharacter\x18\x01 \x01(\tR\tcharacter\x12\x1b\n" +
	"\tsrs_level\x18\x02 \x01(\x05R\bsrsLevel\x12\x1f\n" +
	"\vreview_time\x18\x03 \x01(\x03R\n" +
	"reviewTime2\xde\x02\n" +
	"\x03Srs\x12q\n" +
	"\x15GetAllKanjiReviewData\x12&.aeriqu.kanikaki.srs.IdentifierRequest\x1a,.aeriqu.kanikaki.srs.KanjiReviewDataResponse\"\x000\x01\x12n\n" +
	"\x12GetDueKanjiReviews\x12&.aeriqu.kanikaki.srs.IdentifierRequest\x1a,.aeriqu.kanikaki.srs.KanjiReviewDataResponse\"\x000\x01\x12t\n" +
	"\x15UpdateKanjiReviewData\x12+.aeriqu.kanikaki.srs.KanjiReviewDataRequest\x1a,.aeriqu.kanikaki.srs.KanjiReviewDataResponse\"\x00B)Z'github.com/Aeriqu/kanikaki/services/srsb\x06proto3"

var (
	file_services_srs_proto_srs_proto_rawDescOnce sync.Once
	file_services_srs_proto_srs_proto_rawDescData []byte
)

func file_services_srs_proto_srs_proto_rawDescGZIP() []byte {
	file_services_srs_proto_srs_proto_rawDescOnce.Do(func() {
		file_services_srs_proto_srs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_srs_proto_srs_proto_rawDesc), len(file_services_srs_proto_srs_proto_rawDesc)))
	})
	return file_services_srs_proto_srs_proto_rawDescData
}

var file_services_srs_proto_srs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_srs_proto_srs_proto_goTypes = []any{
	(*IdentifierRequest)(nil),       // 0: aeriqu.kanikaki.srs.IdentifierRequest
	(*KanjiReviewDataRequest)(nil),  // 1: aeriqu.kanikaki.srs.KanjiReviewDataRequest
	(*KanjiReviewDataResponse)(nil), // 2: aeriqu.kanikaki.srs.KanjiReviewDataResponse
}
var file_services_srs_proto_srs_proto_depIdxs = []int32{
	0, // 0: aeriqu.kanikaki.srs.Srs.GetAllKanjiReviewData:input_type -> aeriqu.kanikaki.srs.IdentifierRequest
	0, // 1: aeriqu.kanikaki.srs.Srs.GetDueKanjiReviews:input_type -> aeriqu.kanikaki.srs.IdentifierRequest
	1, // 2: aeriqu.kanikaki.srs.Srs.UpdateKanjiReviewData:input_type -> aeriqu.kanikaki.srs.KanjiReviewDataRequest
	2, // 3: aeriqu.kanikaki.srs.Srs.GetAllKanjiReviewData:output_type -> aeriqu.kanikaki.srs.KanjiReviewDataResponse
	2, // 4: aeriqu.kanikaki.srs.Srs.GetDueKanjiReviews:output_type -> aeriqu.kanikaki.srs.KanjiReviewDataResponse
	2, // 5: aeriqu.kanikaki.srs.Srs.UpdateKanjiReviewData:output_type -> aeriqu.kanikaki.srs.KanjiReviewDataResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_srs_proto_srs_proto_init() }
func file_services_srs_proto_srs_proto_init() {
	if File_services_srs_proto_srs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_srs_proto_srs_proto_rawDesc), len(file_services_srs_proto_srs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_srs_proto_srs_proto_goTypes,
		DependencyIndexes: file_services_srs_proto_srs_proto_depIdxs,
		MessageInfos:      file_services_srs_proto_srs_proto_msgTypes,
	}.Build()
	File_services_srs_proto_srs_proto = out.File
	file_services_srs_proto_srs_proto_goTypes = nil
	file_services_srs_proto_srs_proto_depIdxs = nil
}
