// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: services/srs/proto/srs.proto

package srs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Srs_GetAllKanjiReviewData_FullMethodName = "/aeriqu.kanikaki.srs.Srs/GetAllKanjiReviewData"
	Srs_GetDueKanjiReviews_FullMethodName    = "/aeriqu.kanikaki.srs.Srs/GetDueKanjiReviews"
	Srs_UpdateKanjiReviewData_FullMethodName = "/aeriqu.kanikaki.srs.Srs/UpdateKanjiReviewData"
)

// SrsClient is the client API for Srs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SrsClient interface {
	GetAllKanjiReviewData(ctx context.Context, in *IdentifierRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KanjiReviewDataResponse], error)
	GetDueKanjiReviews(ctx context.Context, in *IdentifierRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KanjiReviewDataResponse], error)
	UpdateKanjiReviewData(ctx context.Context, in *KanjiReviewDataRequest, opts ...grpc.CallOption) (*KanjiReviewDataResponse, error)
}

type srsClient struct {
	cc grpc.ClientConnInterface
}

func NewSrsClient(cc grpc.ClientConnInterface) SrsClient {
	return &srsClient{cc}
}

func (c *srsClient) GetAllKanjiReviewData(ctx context.Context, in *IdentifierRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KanjiReviewDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Srs_ServiceDesc.Streams[0], Srs_GetAllKanjiReviewData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IdentifierRequest, KanjiReviewDataResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Srs_GetAllKanjiReviewDataClient = grpc.ServerStreamingClient[KanjiReviewDataResponse]

func (c *srsClient) GetDueKanjiReviews(ctx context.Context, in *IdentifierRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KanjiReviewDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Srs_ServiceDesc.Streams[1], Srs_GetDueKanjiReviews_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IdentifierRequest, KanjiReviewDataResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Srs_GetDueKanjiReviewsClient = grpc.ServerStreamingClient[KanjiReviewDataResponse]

func (c *srsClient) UpdateKanjiReviewData(ctx context.Context, in *KanjiReviewDataRequest, opts ...grpc.CallOption) (*KanjiReviewDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KanjiReviewDataResponse)
	err := c.cc.Invoke(ctx, Srs_UpdateKanjiReviewData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SrsServer is the server API for Srs service.
// All implementations must embed UnimplementedSrsServer
// for forward compatibility.
type SrsServer interface {
	GetAllKanjiReviewData(*IdentifierRequest, grpc.ServerStreamingServer[KanjiReviewDataResponse]) error
	GetDueKanjiReviews(*IdentifierRequest, grpc.ServerStreamingServer[KanjiReviewDataResponse]) error
	UpdateKanjiReviewData(context.Context, *KanjiReviewDataRequest) (*KanjiReviewDataResponse, error)
	mustEmbedUnimplementedSrsServer()
}

// UnimplementedSrsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSrsServer struct{}

func (UnimplementedSrsServer) GetAllKanjiReviewData(*IdentifierRequest, grpc.ServerStreamingServer[KanjiReviewDataResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetAllKanjiReviewData not implemented")
}
func (UnimplementedSrsServer) GetDueKanjiReviews(*IdentifierRequest, grpc.ServerStreamingServer[KanjiReviewDataResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetDueKanjiReviews not implemented")
}
func (UnimplementedSrsServer) UpdateKanjiReviewData(context.Context, *KanjiReviewDataRequest) (*KanjiReviewDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKanjiReviewData not implemented")
}
func (UnimplementedSrsServer) mustEmbedUnimplementedSrsServer() {}
func (UnimplementedSrsServer) testEmbeddedByValue()             {}

// UnsafeSrsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SrsServer will
// result in compilation errors.
type UnsafeSrsServer interface {
	mustEmbedUnimplementedSrsServer()
}

func RegisterSrsServer(s grpc.ServiceRegistrar, srv SrsServer) {
	// If the following call pancis, it indicates UnimplementedSrsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Srs_ServiceDesc, srv)
}

func _Srs_GetAllKanjiReviewData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(IdentifierRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SrsServer).GetAllKanjiReviewData(m, &grpc.GenericServerStream[IdentifierRequest, KanjiReviewDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Srs_GetAllKanjiReviewDataServer = grpc.ServerStreamingServer[KanjiReviewDataResponse]

func _Srs_GetDueKanjiReviews_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(IdentifierRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SrsServer).GetDueKanjiReviews(m, &grpc.GenericServerStream[IdentifierRequest, KanjiReviewDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Srs_GetDueKanjiReviewsServer = grpc.ServerStreamingServer[KanjiReviewDataResponse]

func _Srs_UpdateKanjiReviewData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KanjiReviewDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SrsServer).UpdateKanjiReviewData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Srs_UpdateKanjiReviewData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SrsServer).UpdateKanjiReviewData(ctx, req.(*KanjiReviewDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Srs_ServiceDesc is the grpc.ServiceDesc for Srs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Srs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aeriqu.kanikaki.srs.Srs",
	HandlerType: (*SrsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateKanjiReviewData",
			Handler:    _Srs_UpdateKanjiReviewData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllKanjiReviewData",
			Handler:       _Srs_GetAllKanjiReviewData_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetDueKanjiReviews",
			Handler:       _Srs_GetDueKanjiReviews_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services/srs/proto/srs.proto",
}
