// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: services/wanikani/proto/wanikani.proto

package wanikani

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WaniKaniTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WanikaniToken string                 `protobuf:"bytes,1,opt,name=wanikani_token,json=wanikaniToken,proto3" json:"wanikani_token,omitempty"`
	AuthToken     string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaniKaniTokenRequest) Reset() {
	*x = WaniKaniTokenRequest{}
	mi := &file_services_wanikani_proto_wanikani_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaniKaniTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaniKaniTokenRequest) ProtoMessage() {}

func (x *WaniKaniTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_wanikani_proto_wanikani_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaniKaniTokenRequest.ProtoReflect.Descriptor instead.
func (*WaniKaniTokenRequest) Descriptor() ([]byte, []int) {
	return file_services_wanikani_proto_wanikani_proto_rawDescGZIP(), []int{0}
}

func (x *WaniKaniTokenRequest) GetWanikaniToken() string {
	if x != nil {
		return x.WanikaniToken
	}
	return ""
}

func (x *WaniKaniTokenRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type KanjiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     string                 `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	WanikaniId    int32                  `protobuf:"varint,2,opt,name=wanikani_id,json=wanikaniId,proto3" json:"wanikani_id,omitempty"`
	WanikaniLevel int32                  `protobuf:"varint,3,opt,name=wanikani_level,json=wanikaniLevel,proto3" json:"wanikani_level,omitempty"`
	Meanings      []string               `protobuf:"bytes,4,rep,name=meanings,proto3" json:"meanings,omitempty"`
	Onyomi        []string               `protobuf:"bytes,5,rep,name=onyomi,proto3" json:"onyomi,omitempty"`
	Kunyomi       []string               `protobuf:"bytes,6,rep,name=kunyomi,proto3" json:"kunyomi,omitempty"`
	Nanori        []string               `protobuf:"bytes,7,rep,name=nanori,proto3" json:"nanori,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KanjiResponse) Reset() {
	*x = KanjiResponse{}
	mi := &file_services_wanikani_proto_wanikani_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KanjiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KanjiResponse) ProtoMessage() {}

func (x *KanjiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_wanikani_proto_wanikani_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KanjiResponse.ProtoReflect.Descriptor instead.
func (*KanjiResponse) Descriptor() ([]byte, []int) {
	return file_services_wanikani_proto_wanikani_proto_rawDescGZIP(), []int{1}
}

func (x *KanjiResponse) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

func (x *KanjiResponse) GetWanikaniId() int32 {
	if x != nil {
		return x.WanikaniId
	}
	return 0
}

func (x *KanjiResponse) GetWanikaniLevel() int32 {
	if x != nil {
		return x.WanikaniLevel
	}
	return 0
}

func (x *KanjiResponse) GetMeanings() []string {
	if x != nil {
		return x.Meanings
	}
	return nil
}

func (x *KanjiResponse) GetOnyomi() []string {
	if x != nil {
		return x.Onyomi
	}
	return nil
}

func (x *KanjiResponse) GetKunyomi() []string {
	if x != nil {
		return x.Kunyomi
	}
	return nil
}

func (x *KanjiResponse) GetNanori() []string {
	if x != nil {
		return x.Nanori
	}
	return nil
}

var File_services_wanikani_proto_wanikani_proto protoreflect.FileDescriptor

const file_services_wanikani_proto_wanikani_proto_rawDesc = "" +
	"\n" +
	"&services/wanikani/proto/wanikani.proto\x12\x18aeriqu.kanikaki.wanikani\"\\\n" +
	"\x14WaniKaniTokenRequest\x12%\n" +
	"\x0ewanikani_token\x18\x01 \x01(\tR\rwanikaniToken\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\"\xdb\x01\n" +
	"\rKanjiResponse\x12\x1c\n" +
	"\tcharacter\x18\x01 \x01(\tR\tcharacter\x12\x1f\n" +
	"\vwanikani_id\x18\x02 \x01(\x05R\n" +
	"wanikaniId\x12%\n" +
	"\x0ewanikani_level\x18\x03 \x01(\x05R\rwanikaniLevel\x12\x1a\n" +
	"\bmeanings\x18\x04 \x03(\tR\bmeanings\x12\x16\n" +
	"\x06onyomi\x18\x05 \x03(\tR\x06onyomi\x12\x18\n" +
	"\akunyomi\x18\x06 \x03(\tR\akunyomi\x12\x16\n" +
	"\x06nanori\x18\a \x03(\tR\x06nanori2v\n" +
	"\bWaniKani\x12j\n" +
	"\vGetAllKanji\x12..aeriqu.kanikaki.wanikani.WaniKaniTokenRequest\x1a'.aeriqu.kanikaki.wanikani.KanjiResponse\"\x000\x01B.Z,github.com/Aeriqu/kanikaki/services/wanikanib\x06proto3"

var (
	file_services_wanikani_proto_wanikani_proto_rawDescOnce sync.Once
	file_services_wanikani_proto_wanikani_proto_rawDescData []byte
)

func file_services_wanikani_proto_wanikani_proto_rawDescGZIP() []byte {
	file_services_wanikani_proto_wanikani_proto_rawDescOnce.Do(func() {
		file_services_wanikani_proto_wanikani_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_wanikani_proto_wanikani_proto_rawDesc), len(file_services_wanikani_proto_wanikani_proto_rawDesc)))
	})
	return file_services_wanikani_proto_wanikani_proto_rawDescData
}

var file_services_wanikani_proto_wanikani_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_wanikani_proto_wanikani_proto_goTypes = []any{
	(*WaniKaniTokenRequest)(nil), // 0: aeriqu.kanikaki.wanikani.WaniKaniTokenRequest
	(*KanjiResponse)(nil),        // 1: aeriqu.kanikaki.wanikani.KanjiResponse
}
var file_services_wanikani_proto_wanikani_proto_depIdxs = []int32{
	0, // 0: aeriqu.kanikaki.wanikani.WaniKani.GetAllKanji:input_type -> aeriqu.kanikaki.wanikani.WaniKaniTokenRequest
	1, // 1: aeriqu.kanikaki.wanikani.WaniKani.GetAllKanji:output_type -> aeriqu.kanikaki.wanikani.KanjiResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_wanikani_proto_wanikani_proto_init() }
func file_services_wanikani_proto_wanikani_proto_init() {
	if File_services_wanikani_proto_wanikani_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_wanikani_proto_wanikani_proto_rawDesc), len(file_services_wanikani_proto_wanikani_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_wanikani_proto_wanikani_proto_goTypes,
		DependencyIndexes: file_services_wanikani_proto_wanikani_proto_depIdxs,
		MessageInfos:      file_services_wanikani_proto_wanikani_proto_msgTypes,
	}.Build()
	File_services_wanikani_proto_wanikani_proto = out.File
	file_services_wanikani_proto_wanikani_proto_goTypes = nil
	file_services_wanikani_proto_wanikani_proto_depIdxs = nil
}
