// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: services/wanikani/proto/wanikani.proto

package wanikani

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WaniKani_GetAllKanji_FullMethodName = "/aeriqu.kanikaki.wanikani.WaniKani/GetAllKanji"
)

// WaniKaniClient is the client API for WaniKani service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WaniKaniClient interface {
	GetAllKanji(ctx context.Context, in *WaniKaniTokenRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KanjiResponse], error)
}

type waniKaniClient struct {
	cc grpc.ClientConnInterface
}

func NewWaniKaniClient(cc grpc.ClientConnInterface) WaniKaniClient {
	return &waniKaniClient{cc}
}

func (c *waniKaniClient) GetAllKanji(ctx context.Context, in *WaniKaniTokenRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KanjiResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WaniKani_ServiceDesc.Streams[0], WaniKani_GetAllKanji_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WaniKaniTokenRequest, KanjiResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WaniKani_GetAllKanjiClient = grpc.ServerStreamingClient[KanjiResponse]

// WaniKaniServer is the server API for WaniKani service.
// All implementations must embed UnimplementedWaniKaniServer
// for forward compatibility.
type WaniKaniServer interface {
	GetAllKanji(*WaniKaniTokenRequest, grpc.ServerStreamingServer[KanjiResponse]) error
	mustEmbedUnimplementedWaniKaniServer()
}

// UnimplementedWaniKaniServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWaniKaniServer struct{}

func (UnimplementedWaniKaniServer) GetAllKanji(*WaniKaniTokenRequest, grpc.ServerStreamingServer[KanjiResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetAllKanji not implemented")
}
func (UnimplementedWaniKaniServer) mustEmbedUnimplementedWaniKaniServer() {}
func (UnimplementedWaniKaniServer) testEmbeddedByValue()                  {}

// UnsafeWaniKaniServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WaniKaniServer will
// result in compilation errors.
type UnsafeWaniKaniServer interface {
	mustEmbedUnimplementedWaniKaniServer()
}

func RegisterWaniKaniServer(s grpc.ServiceRegistrar, srv WaniKaniServer) {
	// If the following call pancis, it indicates UnimplementedWaniKaniServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WaniKani_ServiceDesc, srv)
}

func _WaniKani_GetAllKanji_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WaniKaniTokenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WaniKaniServer).GetAllKanji(m, &grpc.GenericServerStream[WaniKaniTokenRequest, KanjiResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WaniKani_GetAllKanjiServer = grpc.ServerStreamingServer[KanjiResponse]

// WaniKani_ServiceDesc is the grpc.ServiceDesc for WaniKani service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WaniKani_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aeriqu.kanikaki.wanikani.WaniKani",
	HandlerType: (*WaniKaniServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllKanji",
			Handler:       _WaniKani_GetAllKanji_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services/wanikani/proto/wanikani.proto",
}
