// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: services/kanji/proto/kanji.proto

package kanji

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KanjiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kanji         string                 `protobuf:"bytes,1,opt,name=kanji,proto3" json:"kanji,omitempty"`
	AuthToken     string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KanjiRequest) Reset() {
	*x = KanjiRequest{}
	mi := &file_services_kanji_proto_kanji_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KanjiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KanjiRequest) ProtoMessage() {}

func (x *KanjiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_kanji_proto_kanji_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KanjiRequest.ProtoReflect.Descriptor instead.
func (*KanjiRequest) Descriptor() ([]byte, []int) {
	return file_services_kanji_proto_kanji_proto_rawDescGZIP(), []int{0}
}

func (x *KanjiRequest) GetKanji() string {
	if x != nil {
		return x.Kanji
	}
	return ""
}

func (x *KanjiRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type KanjiLevelRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LowerBound    int32                  `protobuf:"varint,1,opt,name=lower_bound,json=lowerBound,proto3" json:"lower_bound,omitempty"`
	UpperBound    int32                  `protobuf:"varint,2,opt,name=upper_bound,json=upperBound,proto3" json:"upper_bound,omitempty"`
	AuthToken     string                 `protobuf:"bytes,3,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KanjiLevelRangeRequest) Reset() {
	*x = KanjiLevelRangeRequest{}
	mi := &file_services_kanji_proto_kanji_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KanjiLevelRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KanjiLevelRangeRequest) ProtoMessage() {}

func (x *KanjiLevelRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_kanji_proto_kanji_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KanjiLevelRangeRequest.ProtoReflect.Descriptor instead.
func (*KanjiLevelRangeRequest) Descriptor() ([]byte, []int) {
	return file_services_kanji_proto_kanji_proto_rawDescGZIP(), []int{1}
}

func (x *KanjiLevelRangeRequest) GetLowerBound() int32 {
	if x != nil {
		return x.LowerBound
	}
	return 0
}

func (x *KanjiLevelRangeRequest) GetUpperBound() int32 {
	if x != nil {
		return x.UpperBound
	}
	return 0
}

func (x *KanjiLevelRangeRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type WaniKaniTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WanikaniToken string                 `protobuf:"bytes,1,opt,name=wanikani_token,json=wanikaniToken,proto3" json:"wanikani_token,omitempty"`
	AuthToken     string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaniKaniTokenRequest) Reset() {
	*x = WaniKaniTokenRequest{}
	mi := &file_services_kanji_proto_kanji_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaniKaniTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaniKaniTokenRequest) ProtoMessage() {}

func (x *WaniKaniTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_kanji_proto_kanji_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaniKaniTokenRequest.ProtoReflect.Descriptor instead.
func (*WaniKaniTokenRequest) Descriptor() ([]byte, []int) {
	return file_services_kanji_proto_kanji_proto_rawDescGZIP(), []int{2}
}

func (x *WaniKaniTokenRequest) GetWanikaniToken() string {
	if x != nil {
		return x.WanikaniToken
	}
	return ""
}

func (x *WaniKaniTokenRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type KanjiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     string                 `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	WanikaniId    int32                  `protobuf:"varint,2,opt,name=wanikani_id,json=wanikaniId,proto3" json:"wanikani_id,omitempty"`
	WanikaniLevel int32                  `protobuf:"varint,3,opt,name=wanikani_level,json=wanikaniLevel,proto3" json:"wanikani_level,omitempty"`
	Meanings      []string               `protobuf:"bytes,4,rep,name=meanings,proto3" json:"meanings,omitempty"`
	Onyomi        []string               `protobuf:"bytes,5,rep,name=onyomi,proto3" json:"onyomi,omitempty"`
	Kunyomi       []string               `protobuf:"bytes,6,rep,name=kunyomi,proto3" json:"kunyomi,omitempty"`
	Nanori        []string               `protobuf:"bytes,7,rep,name=nanori,proto3" json:"nanori,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KanjiResponse) Reset() {
	*x = KanjiResponse{}
	mi := &file_services_kanji_proto_kanji_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KanjiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KanjiResponse) ProtoMessage() {}

func (x *KanjiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_kanji_proto_kanji_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KanjiResponse.ProtoReflect.Descriptor instead.
func (*KanjiResponse) Descriptor() ([]byte, []int) {
	return file_services_kanji_proto_kanji_proto_rawDescGZIP(), []int{3}
}

func (x *KanjiResponse) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

func (x *KanjiResponse) GetWanikaniId() int32 {
	if x != nil {
		return x.WanikaniId
	}
	return 0
}

func (x *KanjiResponse) GetWanikaniLevel() int32 {
	if x != nil {
		return x.WanikaniLevel
	}
	return 0
}

func (x *KanjiResponse) GetMeanings() []string {
	if x != nil {
		return x.Meanings
	}
	return nil
}

func (x *KanjiResponse) GetOnyomi() []string {
	if x != nil {
		return x.Onyomi
	}
	return nil
}

func (x *KanjiResponse) GetKunyomi() []string {
	if x != nil {
		return x.Kunyomi
	}
	return nil
}

func (x *KanjiResponse) GetNanori() []string {
	if x != nil {
		return x.Nanori
	}
	return nil
}

type LoadKanjiResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CharactersAdded []string               `protobuf:"bytes,1,rep,name=characters_added,json=charactersAdded,proto3" json:"characters_added,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoadKanjiResponse) Reset() {
	*x = LoadKanjiResponse{}
	mi := &file_services_kanji_proto_kanji_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadKanjiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadKanjiResponse) ProtoMessage() {}

func (x *LoadKanjiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_kanji_proto_kanji_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadKanjiResponse.ProtoReflect.Descriptor instead.
func (*LoadKanjiResponse) Descriptor() ([]byte, []int) {
	return file_services_kanji_proto_kanji_proto_rawDescGZIP(), []int{4}
}

func (x *LoadKanjiResponse) GetCharactersAdded() []string {
	if x != nil {
		return x.CharactersAdded
	}
	return nil
}

var File_services_kanji_proto_kanji_proto protoreflect.FileDescriptor

const file_services_kanji_proto_kanji_proto_rawDesc = "" +
	"\n" +
	" services/kanji/proto/kanji.proto\x12\x15aeriqu.kanikaki.kanji\"C\n" +
	"\fKanjiRequest\x12\x14\n" +
	"\x05kanji\x18\x01 \x01(\tR\x05kanji\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\"y\n" +
	"\x16KanjiLevelRangeRequest\x12\x1f\n" +
	"\vlower_bound\x18\x01 \x01(\x05R\n" +
	"lowerBound\x12\x1f\n" +
	"\vupper_bound\x18\x02 \x01(\x05R\n" +
	"upperBound\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x03 \x01(\tR\tauthToken\"\\\n" +
	"\x14WaniKaniTokenRequest\x12%\n" +
	"\x0ewanikani_token\x18\x01 \x01(\tR\rwanikaniToken\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\"\xdb\x01\n" +
	"\rKanjiResponse\x12\x1c\n" +
	"\tcharacter\x18\x01 \x01(\tR\tcharacter\x12\x1f\n" +
	"\vwanikani_id\x18\x02 \x01(\x05R\n" +
	"wanikaniId\x12%\n" +
	"\x0ewanikani_level\x18\x03 \x01(\x05R\rwanikaniLevel\x12\x1a\n" +
	"\bmeanings\x18\x04 \x03(\tR\bmeanings\x12\x16\n" +
	"\x06onyomi\x18\x05 \x03(\tR\x06onyomi\x12\x18\n" +
	"\akunyomi\x18\x06 \x03(\tR\akunyomi\x12\x16\n" +
	"\x06nanori\x18\a \x03(\tR\x06nanori\">\n" +
	"\x11LoadKanjiResponse\x12)\n" +
	"\x10characters_added\x18\x01 \x03(\tR\x0fcharactersAdded2\xba\x02\n" +
	"\x05Kanji\x12W\n" +
	"\bGetKanji\x12#.aeriqu.kanikaki.kanji.KanjiRequest\x1a$.aeriqu.kanikaki.kanji.KanjiResponse\"\x00\x12o\n" +
	"\x14GetKanjiByLevelRange\x12-.aeriqu.kanikaki.kanji.KanjiLevelRangeRequest\x1a$.aeriqu.kanikaki.kanji.KanjiResponse\"\x000\x01\x12g\n" +
	"\fLoadAllKanji\x12+.aeriqu.kanikaki.kanji.WaniKaniTokenRequest\x1a(.aeriqu.kanikaki.kanji.LoadKanjiResponse\"\x00B+Z)github.com/Aeriqu/kanikaki/services/kanjib\x06proto3"

var (
	file_services_kanji_proto_kanji_proto_rawDescOnce sync.Once
	file_services_kanji_proto_kanji_proto_rawDescData []byte
)

func file_services_kanji_proto_kanji_proto_rawDescGZIP() []byte {
	file_services_kanji_proto_kanji_proto_rawDescOnce.Do(func() {
		file_services_kanji_proto_kanji_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_kanji_proto_kanji_proto_rawDesc), len(file_services_kanji_proto_kanji_proto_rawDesc)))
	})
	return file_services_kanji_proto_kanji_proto_rawDescData
}

var file_services_kanji_proto_kanji_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_services_kanji_proto_kanji_proto_goTypes = []any{
	(*KanjiRequest)(nil),           // 0: aeriqu.kanikaki.kanji.KanjiRequest
	(*KanjiLevelRangeRequest)(nil), // 1: aeriqu.kanikaki.kanji.KanjiLevelRangeRequest
	(*WaniKaniTokenRequest)(nil),   // 2: aeriqu.kanikaki.kanji.WaniKaniTokenRequest
	(*KanjiResponse)(nil),          // 3: aeriqu.kanikaki.kanji.KanjiResponse
	(*LoadKanjiResponse)(nil),      // 4: aeriqu.kanikaki.kanji.LoadKanjiResponse
}
var file_services_kanji_proto_kanji_proto_depIdxs = []int32{
	0, // 0: aeriqu.kanikaki.kanji.Kanji.GetKanji:input_type -> aeriqu.kanikaki.kanji.KanjiRequest
	1, // 1: aeriqu.kanikaki.kanji.Kanji.GetKanjiByLevelRange:input_type -> aeriqu.kanikaki.kanji.KanjiLevelRangeRequest
	2, // 2: aeriqu.kanikaki.kanji.Kanji.LoadAllKanji:input_type -> aeriqu.kanikaki.kanji.WaniKaniTokenRequest
	3, // 3: aeriqu.kanikaki.kanji.Kanji.GetKanji:output_type -> aeriqu.kanikaki.kanji.KanjiResponse
	3, // 4: aeriqu.kanikaki.kanji.Kanji.GetKanjiByLevelRange:output_type -> aeriqu.kanikaki.kanji.KanjiResponse
	4, // 5: aeriqu.kanikaki.kanji.Kanji.LoadAllKanji:output_type -> aeriqu.kanikaki.kanji.LoadKanjiResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_kanji_proto_kanji_proto_init() }
func file_services_kanji_proto_kanji_proto_init() {
	if File_services_kanji_proto_kanji_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_kanji_proto_kanji_proto_rawDesc), len(file_services_kanji_proto_kanji_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_kanji_proto_kanji_proto_goTypes,
		DependencyIndexes: file_services_kanji_proto_kanji_proto_depIdxs,
		MessageInfos:      file_services_kanji_proto_kanji_proto_msgTypes,
	}.Build()
	File_services_kanji_proto_kanji_proto = out.File
	file_services_kanji_proto_kanji_proto_goTypes = nil
	file_services_kanji_proto_kanji_proto_depIdxs = nil
}
