// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: services/auth/proto/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	OldCredential string                 `protobuf:"bytes,2,opt,name=oldCredential,proto3" json:"oldCredential,omitempty"`
	NewCredential string                 `protobuf:"bytes,3,opt,name=newCredential,proto3" json:"newCredential,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_services_auth_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_services_auth_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ChangePasswordRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *ChangePasswordRequest) GetOldCredential() string {
	if x != nil {
		return x.OldCredential
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewCredential() string {
	if x != nil {
		return x.NewCredential
	}
	return ""
}

func (x *ChangePasswordRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SignupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Credential    string                 `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupRequest) Reset() {
	*x = SignupRequest{}
	mi := &file_services_auth_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupRequest) ProtoMessage() {}

func (x *SignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupRequest.ProtoReflect.Descriptor instead.
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return file_services_auth_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *SignupRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *SignupRequest) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Credential    string                 `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_services_auth_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_services_auth_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *LoginRequest) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_services_auth_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_services_auth_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LogoutRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *LogoutRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_services_auth_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_services_auth_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *RefreshTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_services_auth_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_services_auth_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type IdentifierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentifierResponse) Reset() {
	*x = IdentifierResponse{}
	mi := &file_services_auth_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifierResponse) ProtoMessage() {}

func (x *IdentifierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifierResponse.ProtoReflect.Descriptor instead.
func (*IdentifierResponse) Descriptor() ([]byte, []int) {
	return file_services_auth_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *IdentifierResponse) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_services_auth_proto_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_proto_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_services_auth_proto_auth_proto_rawDescGZIP(), []int{7}
}

func (x *TokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_services_auth_proto_auth_proto protoreflect.FileDescriptor

const file_services_auth_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x1eservices/auth/proto/auth.proto\x12\x14aeriqu.kanikaki.auth\"\x99\x01\n" +
	"\x15ChangePasswordRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12$\n" +
	"\roldCredential\x18\x02 \x01(\tR\roldCredential\x12$\n" +
	"\rnewCredential\x18\x03 \x01(\tR\rnewCredential\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"O\n" +
	"\rSignupRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1e\n" +
	"\n" +
	"credential\x18\x02 \x01(\tR\n" +
	"credential\"N\n" +
	"\fLoginRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1e\n" +
	"\n" +
	"credential\x18\x02 \x01(\tR\n" +
	"credential\"E\n" +
	"\rLogoutRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"K\n" +
	"\x13RefreshTokenRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"4\n" +
	"\x12IdentifierResponse\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\"%\n" +
	"\rTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xbc\x04\n" +
	"\x04Auth\x12i\n" +
	"\x0eChangePassword\x12+.aeriqu.kanikaki.auth.ChangePasswordRequest\x1a(.aeriqu.kanikaki.auth.IdentifierResponse\"\x00\x12R\n" +
	"\x05Login\x12\".aeriqu.kanikaki.auth.LoginRequest\x1a#.aeriqu.kanikaki.auth.TokenResponse\"\x00\x12T\n" +
	"\x06Logout\x12#.aeriqu.kanikaki.auth.LogoutRequest\x1a#.aeriqu.kanikaki.auth.TokenResponse\"\x00\x12`\n" +
	"\fRefreshToken\x12).aeriqu.kanikaki.auth.RefreshTokenRequest\x1a#.aeriqu.kanikaki.auth.TokenResponse\"\x00\x12T\n" +
	"\x06Signup\x12#.aeriqu.kanikaki.auth.SignupRequest\x1a#.aeriqu.kanikaki.auth.TokenResponse\"\x00\x12g\n" +
	"\rValidateToken\x12*.aeriqu.kanikaki.auth.ValidateTokenRequest\x1a(.aeriqu.kanikaki.auth.IdentifierResponse\"\x00B*Z(github.com/Aeriqu/kanikaki/services/authb\x06proto3"

var (
	file_services_auth_proto_auth_proto_rawDescOnce sync.Once
	file_services_auth_proto_auth_proto_rawDescData []byte
)

func file_services_auth_proto_auth_proto_rawDescGZIP() []byte {
	file_services_auth_proto_auth_proto_rawDescOnce.Do(func() {
		file_services_auth_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_auth_proto_auth_proto_rawDesc), len(file_services_auth_proto_auth_proto_rawDesc)))
	})
	return file_services_auth_proto_auth_proto_rawDescData
}

var file_services_auth_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_services_auth_proto_auth_proto_goTypes = []any{
	(*ChangePasswordRequest)(nil), // 0: aeriqu.kanikaki.auth.ChangePasswordRequest
	(*SignupRequest)(nil),         // 1: aeriqu.kanikaki.auth.SignupRequest
	(*LoginRequest)(nil),          // 2: aeriqu.kanikaki.auth.LoginRequest
	(*LogoutRequest)(nil),         // 3: aeriqu.kanikaki.auth.LogoutRequest
	(*RefreshTokenRequest)(nil),   // 4: aeriqu.kanikaki.auth.RefreshTokenRequest
	(*ValidateTokenRequest)(nil),  // 5: aeriqu.kanikaki.auth.ValidateTokenRequest
	(*IdentifierResponse)(nil),    // 6: aeriqu.kanikaki.auth.IdentifierResponse
	(*TokenResponse)(nil),         // 7: aeriqu.kanikaki.auth.TokenResponse
}
var file_services_auth_proto_auth_proto_depIdxs = []int32{
	0, // 0: aeriqu.kanikaki.auth.Auth.ChangePassword:input_type -> aeriqu.kanikaki.auth.ChangePasswordRequest
	2, // 1: aeriqu.kanikaki.auth.Auth.Login:input_type -> aeriqu.kanikaki.auth.LoginRequest
	3, // 2: aeriqu.kanikaki.auth.Auth.Logout:input_type -> aeriqu.kanikaki.auth.LogoutRequest
	4, // 3: aeriqu.kanikaki.auth.Auth.RefreshToken:input_type -> aeriqu.kanikaki.auth.RefreshTokenRequest
	1, // 4: aeriqu.kanikaki.auth.Auth.Signup:input_type -> aeriqu.kanikaki.auth.SignupRequest
	5, // 5: aeriqu.kanikaki.auth.Auth.ValidateToken:input_type -> aeriqu.kanikaki.auth.ValidateTokenRequest
	6, // 6: aeriqu.kanikaki.auth.Auth.ChangePassword:output_type -> aeriqu.kanikaki.auth.IdentifierResponse
	7, // 7: aeriqu.kanikaki.auth.Auth.Login:output_type -> aeriqu.kanikaki.auth.TokenResponse
	7, // 8: aeriqu.kanikaki.auth.Auth.Logout:output_type -> aeriqu.kanikaki.auth.TokenResponse
	7, // 9: aeriqu.kanikaki.auth.Auth.RefreshToken:output_type -> aeriqu.kanikaki.auth.TokenResponse
	7, // 10: aeriqu.kanikaki.auth.Auth.Signup:output_type -> aeriqu.kanikaki.auth.TokenResponse
	6, // 11: aeriqu.kanikaki.auth.Auth.ValidateToken:output_type -> aeriqu.kanikaki.auth.IdentifierResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_auth_proto_auth_proto_init() }
func file_services_auth_proto_auth_proto_init() {
	if File_services_auth_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_auth_proto_auth_proto_rawDesc), len(file_services_auth_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_auth_proto_auth_proto_goTypes,
		DependencyIndexes: file_services_auth_proto_auth_proto_depIdxs,
		MessageInfos:      file_services_auth_proto_auth_proto_msgTypes,
	}.Build()
	File_services_auth_proto_auth_proto = out.File
	file_services_auth_proto_auth_proto_goTypes = nil
	file_services_auth_proto_auth_proto_depIdxs = nil
}
